from force_bdss.api import BaseCSVWriter, BaseCSVWriterFactory


class CSVWriter(BaseCSVWriter):
    """
    ITWM CSVWriter extends the header and data rows generated by the
    BaseCSVWriter by adding the `weights` entries from the MCO progress
    events.
    """

    def parse_progress_event(self, event):
        event_datavalues = super().parse_progress_event(event)
        event_datavalues.extend(event.weights)
        return event_datavalues


class CSVWriterFactory(BaseCSVWriterFactory):
    def get_identifier(self):
        return "csv_writer"

    def get_name(self):
        return "CSV Writer"

    def get_listener_class(self):
        return CSVWriter
